# Deployment object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movr-deployment
  labels:
    app: movr-app
spec:
  selector:
    matchLabels:
      app: movr-app
  replicas: 2
  template:
    metadata:
      labels:
        app: movr-app
    spec:
      containers:
        - image: gcr.io/movr-test-259013/movr-app:v1
          name: movr-app
          ports:
            - containerPort: 8080
---
# Service object
apiVersion: v1
kind: Service
metadata:
  labels:
    app: movr-app
  name: movr-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
    nodePort: 30062
  selector:
    app: movr-app
  type: NodePort
